### ISSUE TITLE
Not sure how to install

### ISSUE THREAD

**Issue by angelineyeow** [nmartin84/logseq-theme-colors#2]
Sorry, don't really have coding experience/knowledge so I'm having trouble importing this into Logseq.

**Comment by nmartin84** [comment]
@angelineyeow no worries, I am planning to release this to the marketplace soon. It'll be named "Fluid". I'll post a reply here when it's available.

**Comment by angelineyeow** [comment]
That would be great, thank you!

Would it also be possible to create a theme based on this? https://github.com/soft-aesthetic/soft-era

**Comment by nmartin84** [comment]
@angelineyeow - you can test this out now.. I'm re-branding my old solarized theme as Flow. If you go to the marketplace -> Themes -> Select Install on "Solarized theme" and that'll get you the theme. Also I should be able to add your color theme soft-era no problem (nice colors!). Give me a little time and i'll add it to the base theme.

**Comment by nmartin84** [comment]
@angelineyeow - Ok soft era has been added. Let me know what you think. I may tweak it a little to make the primary text color more readable. 
![image](https://user-images.githubusercontent.com/38045018/192419169-9624bbeb-1de2-4b56-a3d8-f3bc0cf8f1ae.png)

**Comment by angelineyeow** [comment]
looks great! thank you so much 🙏

**Comment by angelineyeow** [comment]
just downloaded it and it looks great so far! there is a small issue though - upon first downloading it, my logseq was set to dark mode, then when i switched it to light mode and opened the theme switcher window, the window had no background. but after changing it to the soft era theme the theme switcher works fine

**Comment by nmartin84** [comment]
no problem! I have noticed that other bug myself, but not real sure how to avoid it or if it's a bug with logseq itself. I'll keep digging at it and see if I can eventually fix it. Feel free to share any other feedback if you run into issues.
